set nocompatible              " be iMproved, required

let $VIM='$HOME/.vim'

filetype off                  " required
" keep myplugins before plug/vundle in order not to break padoc.vim
" if swapped: pandoc_markdown = 0 uneffective
source $VIM/myplugins.vim
"source $VIM/vundle.vim
source $VIM/plug.vim

source $VIM/my.vim
source $VIM/map.vim
source $VIM/submodes.vim
source $VIM/style.vim
source $VIM/abbreviations.vim

" FileType settings have top priority, so they should overwrite everything else
" and they do
