# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

. $HOME/.config/sh/shrc

mkdir -p $XDG_CACHE_HOME/zsh/

# Path to other zshrc files
export ZSH_DIR="$SH_DIR/zsh"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"


if [ -f $ZSH_DIR/zinit-pre.zsh ]; then
    . $ZSH_DIR/zinit-pre.zsh
fi

# ┌──────────────┐
# │ Zinit stuffs │
# └──────────────┘

if [ -f $ZSH_DIR/zinit.zsh ]; then
    . $ZSH_DIR/zinit.zsh
fi

# User configuration

# ┌───────────────┐
# │ My zsh stuffs │
# └───────────────┘

if [ -f $ZSH_DIR/my.zsh ]; then
    . $ZSH_DIR/my.zsh
fi

if [ -f $ZSH_DIR/keys.zsh ]; then
    . $ZSH_DIR/keys.zsh
fi

if [ -f $ZSH_DIR/completion.zsh ]; then
    . $ZSH_DIR/completion.zsh
fi

if [ -f $ZSH_DIR/aliases.zsh ]; then
    . $ZSH_DIR/aliases.zsh
fi

eval "$(starship init zsh)"
