#!/usr/bin/sh

# ----------------
# load vars
# ----------------

layouts_file="$KB_LAYOUTS_DIR/layouts"
if [ ! -f $layouts_file ]; then
  echo "Nothing done."
  exit
else
  layouts=`cat $layouts_file`
  kb_l_len=$(echo $layouts | grep -o ':' | wc -l)
  #echo $kb_l_len
fi

current_file="$KB_LAYOUTS_DIR/current_layout"
if [ ! -f $current_file ]; then
  current_layout=1
else
  current_layout=`cat $current_file`
fi

# ----------------
# update layout
# ----------------

if [ $current_layout -eq $kb_l_len ]; then
  current_layout=1
else
  current_layout=$((current_layout + 1))
fi
echo $current_layout > $current_file

layout_file=$(echo $layouts | cut -d':' -f$(($current_layout + 1)))
xmodmap $layout_file
echo $(basename $layout_file) | cut -d'.' -f1
#echo $current_layout
cat $layout_file
