#!/usr/bin/env python3
import argparse
import pathlib
import re

here = pathlib.Path(__file__).parent.absolute()
cwd = pathlib.Path.cwd().absolute()


def parse():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-n", "--name", type=str, default="env", help="environment name"
    )
    parser.add_argument("-r", "--root", type=str, default=None, help="environment name")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse()

    env_root = str(pathlib.Path(args.root).absolute() if args.root is not None else cwd)
    env_name = args.name

    venv_this = (here / "venv_this").read_text()
    variables = re.finditer(r"\{\{\s*(\w*)\s*\}\}", venv_this, re.MULTILINE)

    for v in variables:
        name = v.group(1)
        if name.isidentifier():
            venv_this = venv_this.replace(v.group(0), locals()[name])

    (cwd / ".venv_this").write_text(venv_this)
