#!/bin/bash

# QUERY=("tag:inbox")
QUERY+=("tag:notify")
# QUERY+=("AND tag:important")
# QUERY+=("AND NOT query:{lists,junk}")
QUERY+=("AND NOT query:{junk}")

search_result=$(notmuch search --output=threads --format=json "${QUERY[*]}" | jq '.[]' -r)

for id in $search_result; do
  mail_info=$(notmuch show --format=json $id)

  echo $id
  author=$(jq '.[0][0][0].headers.From' -r <<<$mail_info)
  subject=$(jq '.[0][0][0].headers.Subject' -r <<<$mail_info)
  date=$(jq '.[0][0][0].headers.Date' -r <<<$mail_info)
  mailbox=$(notmuch address --output="recipients" $id | rg -i 'ale' | rg -i 'candido')

  notify-send \
    "${subject}" \
    "<i>From:</i> ${author}\n<i>To:</i> ${mailbox}\n<i>Date:</i> ${date}" \
    --icon neomutt \
    --category email.arrived
  sleep 0.3
done
notmuch tag -notify -- tag:notify
