#!/bin/sh
notmuch new
# retag all "new" messages "inbox" and "unread"
notmuch tag +inbox +unread +notify -new -- tag:new
# tag all messages from "me" as sent and remove tags inbox and unread
notmuch tag -new -inbox +sent -- from:alessandro.candido@mi.infn.it or from:alessandro.candido1@unimi.it

notify-new-mail
