#!/usr/bin/env bash

if [ $# -eq 0 ]; then
	echo "What manual page do you want?"
	exit 0
elif ! man -w "$@" >/dev/null; then
	# Check that manpage exists to prevent visual noise.
	exit 1
fi

RANDOM_FILENAME="ciao"
${EDITOR:-vim} $RANDOM_FILENAME -c "SuperMan $* | bdelete 1"
