#!/usr/bin/env python3

import argparse
import subprocess


def parse():
    parser = argparse.ArgumentParser()
    parser.add_argument("extra", nargs="?", help="extra filters")
    parser.add_argument(
        "-np",
        "--no-priority",
        action="store_false",
        dest="priority",
        help="sort by priority",
    )
    return parser.parse_args()


def run(extra, priority=True):
    p = "-p" if priority else ""
    subtasks = "--namespace" if priority else "--indent"
    filters = "#Work"
    if extra is not None:
        filters += f"& {extra}"

    todo = subprocess.Popen(
        f"unbuffer todoist {subtasks} list {p} --filter".split() + [filters],
        stdout=subprocess.PIPE,
    )
    subprocess.run("less -r".split(), stdin=todo.stdout)


if __name__ == "__main__":
    args = parse()
    print(args)
    run(args.extra, priority=args.priority)
