#!/bin/bash

# example: ./compile_style nord.style

if [ -z $1 ]; then
    echo "style file required --> nothing done"
    exit 1
fi

ifs=$IFS
IFSf=' '
IFSl=' ='

IFS=$IFSf

replace_rule=""

while read -r line; do
    if [[ ${line:0:1} == '#' || -z "${line// }" ]]; then
        continue
    fi

    IFS=$IFSl
    read -ra ARGS <<< "$line"
    IFS=$IFSf

    var=${ARGS[0]}
    value=${ARGS[1]//\'}

    replace_rule="${replace_rule}-e s/#{$var}/$value/g "
done < "$1"

#echo "sed $replace_rule pre.local.tmux > local.tmux"
sed $replace_rule pre.local.tmux > local.tmux

IFS=$ifs
